version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*eslint*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    open-pull-requests-limit: 0
